# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce089111e6a3db558d3c2ebbf7fc7fc4914f6fca49dfb97e2a307d31c196e907b1afcc17abc5dc676fd425778074a25c022dead14771fd3119536280b192b62a

test:
  secret_key_base: fab0566b21acfbea3a01b03f395d1ad69c773d5be49b8caf8b3acc53ef84382631e70a07ac06e1e764720937b3476d82a6a1ba59e227e32c62231f5b95e310a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
